apiVersion: v1
kind: Pod
metadata:
  name: image-digest-using-pod
spec:
  containers:
  - name: busybox
    image: busybox:stable-uclibc@sha256:e354760f603a5ff0949538be4308971455f1a0094d26ec44d77ce0d57400b974
    command: ['sh', '-c', 'sleep 999']